sonar.projectKey=sport_devops
sonar.projectName=sport_devops
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/coverage/**,frontend/build/**,frontend/public/**
